Fix container build issues by removing replace directive
- Remove replace directive for github.com/openshift/service-ca-operator => ../../
- Create local constants file to avoid dependency on main module
- Copy required constants from pkg/controller/api to util/constants.go
- Update all util files to use local constants instead of importing api package
- Remove service-ca-operator dependency from go.mod
- Regenerate vendor directory to be consistent

This fixes the container build error:
'cannot find module providing package github.com/openshift/service-ca-operator/pkg/controller/api: import lookup disabled by -mod=vendor'

The replace directive was causing issues in container builds where the relative path ../../ doesn't exist.